/**
 * Centralized Permission Catalog
 * 
 * Format: RESOURCE:ACTION
 * 
 * Scopes:
 * - GLOBAL: Platform-level permissions, assigned directly to users
 * - COMPANY: Company-level permissions, assigned via roles
 */

export const PERMISSIONS = {
  // PLATFORM
  PLATFORM: {
    MANAGE_USERS: 'PLATFORM:MANAGE_USERS',
    MANAGE_PERMISSIONS: 'PLATFORM:MANAGE_PERMISSIONS',
    VIEW_ANALYTICS: 'PLATFORM:VIEW_ANALYTICS',
    MANAGE_SETTINGS: 'PLATFORM:MANAGE_SETTINGS',
  },

  // COMPANY
  COMPANY: {
    CREATE: 'COMPANY:CREATE',
    EDIT_SETTINGS: 'COMPANY:EDIT_SETTINGS',
    DELETE: 'COMPANY:DELETE',
    VIEW_DETAILS: 'COMPANY:VIEW_DETAILS',
    VIEW_ANALYTICS: 'COMPANY:VIEW_ANALYTICS',
    EXPORT_DATA: 'COMPANY:EXPORT_DATA',
  },

  // MEMBERS
  MEMBER: {
    INVITE: 'MEMBER:INVITE',
    REMOVE: 'MEMBER:REMOVE',
    EDIT_ROLE: 'MEMBER:EDIT_ROLE',
    VIEW_LIST: 'MEMBER:VIEW_LIST',
    VIEW_DETAILS: 'MEMBER:VIEW_DETAILS',
  },

  // ROLES
  ROLE: {
    CREATE: 'ROLE:CREATE',
    EDIT: 'ROLE:EDIT',
    DELETE: 'ROLE:DELETE',
    VIEW: 'ROLE:VIEW',
    ASSIGN_PERMISSIONS: 'ROLE:ASSIGN_PERMISSIONS',
  },

  // INVOICES
  INVOICE: {
    CREATE: 'INVOICE:CREATE',
    EDIT: 'INVOICE:EDIT',
    DELETE: 'INVOICE:DELETE',
    VIEW: 'INVOICE:VIEW',
    APPROVE: 'INVOICE:APPROVE',
    EXPORT: 'INVOICE:EXPORT',
  },

  // REPORTS
  REPORT: {
    CREATE: 'REPORT:CREATE',
    EDIT: 'REPORT:EDIT',
    DELETE: 'REPORT:DELETE',
    VIEW: 'REPORT:VIEW',
    EXPORT: 'REPORT:EXPORT',
    SCHEDULE: 'REPORT:SCHEDULE',
  },

  // TIME TRACKING
  TIME: {
    TRACK: 'TIME:TRACK',
    EDIT_OWN: 'TIME:EDIT_OWN',
    EDIT_ALL: 'TIME:EDIT_ALL',
    APPROVE: 'TIME:APPROVE',
    VIEW_REPORTS: 'TIME:VIEW_REPORTS',
    EXPORT: 'TIME:EXPORT',
  },

  // CLIENTS
  CLIENT: {
    CREATE: 'CLIENT:CREATE',
    EDIT: 'CLIENT:EDIT',
    DELETE: 'CLIENT:DELETE',
    VIEW: 'CLIENT:VIEW',
  },

  // CATEGORIES
  CATEGORY: {
    CREATE: 'CATEGORY:CREATE',
    EDIT: 'CATEGORY:EDIT',
    DELETE: 'CATEGORY:DELETE',
    VIEW: 'CATEGORY:VIEW',
  },

  // CALENDAR
  CALENDAR: {
    CREATE: 'CALENDAR:CREATE',
    EDIT_OWN: 'CALENDAR:EDIT_OWN',
    EDIT_ALL: 'CALENDAR:EDIT_ALL',
  },
} as const;

// Type helpers
export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS][keyof typeof PERMISSIONS[keyof typeof PERMISSIONS]];
